# Generated by Django 5.0.2 on 2025-08-27 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interview', '0002_alter_attempt_options_alter_question_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='attempt',
            name='ai_feedback',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='attempt',
            name='raw_ai_response',
            field=models.TextField(blank=True),
        ),
    ]
